//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_PI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesProjeto_PI : DbContext
    {
        public EntidadesProjeto_PI()
            : base("name=EntidadesProjeto_PI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doadore> Doadores { get; set; }
        public virtual DbSet<Endereco> Enderecos { get; set; }
        public virtual DbSet<Imagen> Imagens { get; set; }
        public virtual DbSet<Ong> Ongs { get; set; }
        public virtual DbSet<Projeto> Projetos { get; set; }
        public virtual DbSet<Sobre> Sobres { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Voluntario> Voluntarios { get; set; }
    }
}
