//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_PI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sobre
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string texto { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idImagem { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
