-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 22:11:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Projeto_PI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projeto_PI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projeto_PI` ;
USE `Projeto_PI` ;

-- -----------------------------------------------------
-- Table `Projeto_PI`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Endereco` (`cep` ASC, `numero` ASC, `bairro` ASC, `rua` ASC, `cidade` ASC, `estado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Imagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `idEndereco` INT NOT NULL,
  `idImagem` INT NULL,
  `frase` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC),
  INDEX `idImagem_Imagens_id_Imagens_idx` (`idImagem` ASC),
  UNIQUE INDEX `idImagem_UNIQUE` (`idImagem` ASC),
  CONSTRAINT `idEndereco_Usuarios_id_Enderecos`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `Projeto_PI`.`Enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idImagem_Usuarios_id_Imagens`
    FOREIGN KEY (`idImagem`)
    REFERENCES `Projeto_PI`.`Imagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Ongs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Ongs` (
  `id` INT(11) NOT NULL,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(10) NOT NULL,
  `representante` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `razaoSocial_UNIQUE` (`razaoSocial` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  CONSTRAINT `Id_Ongs_Id_Usuarios`
    FOREIGN KEY (`id`)
    REFERENCES `Projeto_PI`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Doadores` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  CONSTRAINT `Id_Doadores_IdUsuarios`
    FOREIGN KEY (`id`)
    REFERENCES `Projeto_PI`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Projetos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `banner` INT NOT NULL,
  `meta` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `banner_UNIQUE` (`banner` ASC),
  CONSTRAINT `idUsuario_Projetos_id_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Projeto_PI`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `banner_Projetos_id_Imagens`
    FOREIGN KEY (`banner`)
    REFERENCES `Projeto_PI`.`Imagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Apoios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Apoios` (
  `idProjeto` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idProjeto`, `idUsuario`),
  INDEX `idUsuario_Apoios_id_Usuarios_idx` (`idUsuario` ASC),
  CONSTRAINT `idProjeto_Apoios_id_Projeto`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `Projeto_PI`.`Projetos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario_Apoios_id_Usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Projeto_PI`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Sobre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Sobre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idImagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_Sobre_id_Usuario_idx` (`idUsuario` ASC),
  UNIQUE INDEX `idImagem_UNIQUE` (`idImagem` ASC),
  CONSTRAINT `idUsuario_Sobre_id_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Projeto_PI`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idImagem_Sobre_id_Imagens`
    FOREIGN KEY (`idImagem`)
    REFERENCES `Projeto_PI`.`Imagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_PI`.`Voluntarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_PI`.`Voluntarios` (
  `idOng` INT NOT NULL AUTO_INCREMENT,
  `idDoador` INT NOT NULL,
  `Situacao` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idOng`, `idDoador`),
  INDEX `idDoador_Voluntarios_id_Doador_idx` (`idDoador` ASC),
  CONSTRAINT `idOng_Voluntarios_id_Ong`
    FOREIGN KEY (`idOng`)
    REFERENCES `Projeto_PI`.`Ongs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDoador_Voluntarios_id_Doador`
    FOREIGN KEY (`idDoador`)
    REFERENCES `Projeto_PI`.`Doadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Projeto_PI` ;

-- -----------------------------------------------------
-- function getIdUsuario
-- -----------------------------------------------------

DELIMITER $$
USE `Projeto_PI`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `getIdUsuario`(emailUsuario varchar(100)) RETURNS int(11)
BEGIN 
  declare retorno int;
  select id into retorno from Usuarios where email = emailUsuario;
  RETURN retorno; 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure setOngs
-- -----------------------------------------------------

DELIMITER $$
USE `Projeto_PI`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `setOngs`(nome varchar(45), email varchar(100),
 senha varchar(45), razaoSocial varchar(45), cnpj varchar(14),
 telefone varchar(10), representante varchar(45), cargo varchar(45))
begin
  declare exit handler for sqlexception begin
    select "houve um erro ao inserir no banco" as 'Erro';
    rollback;
    end;
  start transaction;
    call setUsuario(nome, email, senha);
    insert into Ongs values(getIdUsuario(email), razaoSocial, cnpj,telefone,representante,cargo);
  commit;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure setUsuario
-- -----------------------------------------------------

DELIMITER $$
USE `Projeto_PI`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `setUsuario`(nome varchar(45), email varchar(100), senha varchar(45))
begin 
  insert into Usuarios(nome, email, senha) values(nome, email, senha);
end$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
